import { StyleSheet } from "react-native";

// The same slate, indigo, emerald and rose palette used by the supplied prototype.
export const colors = {
  page: "#020617",
  surface: "#0f172a",
  border: "#1e293b",
  text: "#f1f5f9",
  muted: "#94a3b8",
  primary: "#1266b0",
  green: "#34d399",
  red: "#fb7185",
};
export const styles = StyleSheet.create({
  workspace: { width: "100%", maxWidth: 1240, alignSelf: "center", gap: 20 },
  workspaceWide: { flexDirection: "row", alignItems: "flex-start" },
  mainColumn: { minWidth: 0, gap: 16, width: "100%" },
  contextColumn: { minWidth: 0, gap: 16, width: "100%" },
  contextCard: {
    padding: 20,
    borderRadius: 18,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 12,
  },
  eyebrow: {
    color: "#93c5fd",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1.6,
  },
  siteName: {
    color: colors.text,
    fontSize: 24,
    lineHeight: 32,
    fontWeight: "700",
    flexShrink: 1,
  },
  sectionTitle: { color: colors.text, fontSize: 16, fontWeight: "700" },
  mealRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 14,
    borderRadius: 12,
    backgroundColor: colors.page,
  },
  openMeal: {
    backgroundColor: "#052e2b",
    borderWidth: 1,
    borderColor: "#176c59",
  },
  recordControls: {
    flexDirection: "row",
    flexWrap: "wrap",
    width: "100%",
    gap: 12,
  },
  recordControl: { flexGrow: 1, flexBasis: 190, gap: 8 },
  totalsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    width: "100%",
    gap: 10,
  },
  totalCard: {
    flexGrow: 1,
    flexBasis: 120,
    padding: 16,
    gap: 6,
    backgroundColor: colors.page,
    borderRadius: 12,
  },
  totalNumber: { color: colors.text, fontSize: 28, fontWeight: "700" },

  screen: { flex: 1, backgroundColor: colors.page },
  header: {
    padding: 16,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderColor: colors.border,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  brand: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
    minWidth: 220,
  },
  logo: {
    backgroundColor: colors.primary,
    borderRadius: 8,
    width: 30,
    height: 30,
    textAlign: "center",
    textAlignVertical: "center",
    color: "#fff",
    fontSize: 20,
  },
  title: { color: colors.text, fontSize: 15, fontWeight: "700" },
  subtitle: { color: colors.muted, fontSize: 11, marginTop: 3 },
  text: { color: colors.text, fontSize: 14, lineHeight: 22 },
  muted: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 20,
    textAlign: "center",
  },
  heading: {
    color: colors.text,
    fontSize: 26,
    fontWeight: "700",
    textAlign: "center",
  },
  content: {
    flexGrow: 1,
    justifyContent: "flex-start",
    padding: 24,
    alignItems: "center",
    gap: 20,
  },
  panel: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 20,
    padding: 28,
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
    alignItems: "center",
    gap: 16,
  },
  meals: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 20,
    padding: 14,
    borderBottomWidth: 1,
    borderColor: colors.border,
    backgroundColor: "#0f172a80",
  },
  meal: { alignItems: "center", gap: 2 },
  input: {
    color: colors.text,
    backgroundColor: colors.page,
    borderWidth: 1,
    borderColor: "#334155",
    padding: 14,
    borderRadius: 10,
    width: "100%",
    fontSize: 15,
  },
  button: {
    backgroundColor: colors.primary,
    minHeight: 48,
    padding: 14,
    borderRadius: 10,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  buttonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
    textAlign: "center",
  },
  secondary: { backgroundColor: colors.border },
  disabled: { opacity: 0.45 },
  error: {
    color: colors.red,
    fontSize: 13,
    textAlign: "center",
    lineHeight: 20,
  },
  photo: {
    width: 192,
    height: 192,
    borderRadius: 16,
    backgroundColor: colors.page,
  },
  camera: { width: "100%", height: 260, overflow: "hidden", borderRadius: 16 },
  badge: { color: colors.green, fontSize: 12, fontWeight: "600" },
  footer: {
    padding: 16,
    borderTopWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  historyRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    paddingVertical: 8,
  },
  scanFrame: {
    width: 96,
    height: 96,
    borderWidth: 2,
    borderColor: "#6366f1",
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    margin: 10,
  },
  scanIcon: { color: "#60a5fa", fontSize: 52 },
});
